
# This is the some errors while using pytorch

- [x] TypeError: module.__init__() takes at most 2 arguments (3 given) when create self-defined dataset inherited from `torch.utils.data.Dataset`, [solution](00001.md)